daysUntilStale: 60

daysUntilClose: 7

exemptLabels:
  - pinned

staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it hasn't had any
  activity in 60 days. It will be closed in 7 days if no further activity occurs
  (e.g. changing labels, comments, commits, etc.). Please feel free to
  tag a maintainer and ask them to remove the label if you think it doesn't apply.
  Thank you for submitting this issue and helping make Ritchie a better product!

pulls:
  markComment: >
    This PR has been automatically marked as stale because it hasn't had any
    activity in 60 days. It will be closed in 7 days if no further activity occurs
    (e.g. changing labels, comments, commits, etc.). Please feel free to
    tag a maintainer and ask them to remove the label if you think it doesn't apply.
    Thank you for submitting this PR and helping make Ritchie a better product!
