run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  modules-download-mode: vendor
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  golint:
    min-confidence: 0.8
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - gci
    - testpackage
    - nlreturn
    - gomnd
    - wsl
    - goerr113
    - scopelint
    - whitespace
  presets:
  fast: false


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gocritic
        - gocyclo
        - gosec
        - lll
        - goconst
        - unparam
        - unused
        - sqlclosecheck

    - linters:
        - lll
      source: "^//go:generate "

    # error strings should not be capitalized
    - linters:
        - stylecheck
      text: "ST1005:"

    #  at least one file in a package should have a package comment
    - linters:
        - stylecheck
      text: "ST1000:"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
