run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  modules-download-mode: vendor
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  golint:
    min-confidence: 0.8
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - gci
  presets:
  fast: false


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gocritic
        - gocyclo
        - gosec
        - lll
        - goconst
        - unparam
        - unused
        - sqlclosecheck

    - linters:
        - lll
      source: "^//go:generate "

    # Exclude "package comment" as unnececcary
    - linters:
        - stylecheck
      text: "ST1000:"

    # Exclude "same receiver name" warnings
    - linters:
        - stylecheck
      text: "ST1016:"

    # Exclude naming warnings (at least for now)
    - linters:
        - stylecheck
      text: "ST1003:"

    # Exclude function,var,const comment prefix warning for now
    - linters:
        - stylecheck
      text: "ST1020:"
    - linters:
        - stylecheck
      text: "ST1021:"
    - linters:
        - stylecheck
      text: "ST1022:"

    # Exclude "always receives" warnings as false positives
    - linters:
        - unparam
      text: "always receives"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
