FROM centos:7

# Install needed software and users
USER root
RUN groupadd -r circleci && useradd -r -d /home/circleci -m -g circleci circleci

RUN curl -s -L https://bintray.com/mh-cbon/rpm/rpm > /etc/yum.repos.d/w.repo 

RUN yum install -y epel-release && \
    yum install -y git tar curl wget sudo make yum-utils device-mapper-persistent-data lvm2 && \
    yum clean all && \
    yum install go-bin-rpm changelog rpm-build -y --quiet

RUN echo "%circleci        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers

USER circleci
