name: build for request

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch: # Can be triggered manually through the ACTIONS tab on Github GUI.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: golangci-lint install
        run: |
          download=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
          wget -O- -q $download |sudo sh -s -- -b /go/bin/ v1.31.0
      - name: lint files
        run: |
          /go/bin/golangci-lint run --issues-exit-code=1 --timeout=5m -v ./...
  unit-test:
    env:
      TEST_RESULTS_DIR: bin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install gotestsum
        run: |
          curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v0.4.2/gotestsum_0.4.2_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum
      - name: Run Unit Tests
        run: |
          mkdir -p ${{ env.TEST_RESULTS_DIR }}
          . ./run-tests-ci.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.txt
          directory: ${{ env.TEST_RESULTS_DIR }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
