name: Generate Doc Releases

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Clone ZupIT/docs-ritchie PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: 'ZupIT'
          repository: 'docs-ritchie'
      - name: Generate release on documentation repo
        run: |
          cd docs-ritchie
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b test-${{ steps.vars.outputs.tag }}
          git add . ; git commit -m "Creating new release according the Ritchie CLI tag ${{ steps.vars.outputs.tag }}"
          git push origin release-${{ steps.vars.outputs.tag }}
