name: List Artifacts And Edit Pull Request
on:
  workflow_run:
    workflows: ["Build PR to QA"]
    types: [completed]

jobs:
  list-artifacts-edit-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: List artifacts
        id: list-artifacts
        uses: chiaretto/github-action-list-artifacts-pr@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "
        ### This pull request generated the following artifacts

  To test the health and quality of this implementation, download the respective binary
  for your operating system, unzip and directly run the binary like the examples below.

  - **Windows**\r
  Download the file: **[rit-windows.zip](${{ steps.list-artifacts.outputs.rit-windows}})**\r
  Unzip to some folder like `C:\\home\\user\\downloads\\pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Access the folder: `cd C:\\home\\user\\downloads\\pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Directly call the binary: `.\\rit.exe --version` or `.\\rit.exe name of formula`\r
  \r\r
  - **Linux**\r
  Download the file: **[rit-linux.zip](${{ steps.list-artifacts.outputs.rit-linux}})**\r
  Unzip to some folder like /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Access the folder: cd /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Directly call the binary: ./rit --version` or `./rit.exe name of formula`\r
  \r\r
  - **MacOS**\r
  Download the file: **[rit-macos.zip](${{ steps.list-artifacts.outputs.rit-macos}})**\r
  Unzip to some folder like: `/home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Access the folder: `cd /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Directly call the binary: `./rit --version` or `./rit.exe name of formula`\r
        "
          replace-last-message: true