name: Test Credential Commands

# TXT files used for ASSERT are located on the /testdata/gha_workflows directory.

# To help you coding your workflow tests, you can use CAT commands to show each file you will compare on the workflow window on Github.

# EXAMPLE:
#   rit list credential > check1.txt
#   cat check1.txt
#   cat testdata/gha_workflows/credential_workflow/assert1.txt
#   diff check1.txt testdata/gha_workflows/credential_workflow/assert1.txt

on:
  workflow_dispatch: # Can be triggered manually through the ACTIONS tab on Github GUI.
  push:
    paths: # Will trigger on PUSH event that update at least one of those files.
      - '**/cmd.go'
      - '**/delete_test.go'
      - '**/delete.go'
      - '**/delete_credential_test.go'
      - '**/delete_credential.go'
      - '**/list_credential_test.go'
      - '**/list_credential.go'
      - '**/list_test.go'
      - '**/list.go'
      - '**/set_credential_test.go'
      - '**/set_credential.go'
      - '**/set_test.go'
      - '**/set.go'

  pull_request:
    paths: # Will trigger on PULL_REQUEST event that update at least one of those files.
      - '**/cmd.go'
      - '**/delete_test.go'
      - '**/delete.go'
      - '**/delete_credential_test.go'
      - '**/delete_credential.go'
      - '**/list_credential_test.go'
      - '**/list_credential.go'
      - '**/list_test.go'
      - '**/list.go'
      - '**/set_credential_test.go'
      - '**/set_credential.go'
      - '**/set_test.go'
      - '**/set.go'

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
            rit init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT LIST CREDENTIAL command (1)
          run: rit list credential > check1.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check1.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT SET CREDENTIAL command
          run: rit set credential --provider=github --fields=username,email,token --values=test,test,test
        - name: RIT LIST CREDENTIAL command (2)
          run: rit list credential > check2.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check2.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT DELETE CREDENTIAL command
          run: rit delete credential --provider=github
        - name: RIT LIST CREDENTIAL command (3)
          run: rit list credential > check3.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check3.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert3.txt
            expected_result: PASSED

  macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-mac && sudo mv ./dist/darwin/rit /usr/local/bin
            rit init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT LIST CREDENTIAL command (1)
          run: rit list credential > check1.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check1.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT SET CREDENTIAL command
          run: rit set credential --provider=github --fields=username,email,token --values=test,test,test
        - name: RIT LIST CREDENTIAL command (2)
          run: rit list credential > check2.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check2.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT DELETE CREDENTIAL command
          run: rit delete credential --provider=github
        - name: RIT LIST CREDENTIAL command (3)
          run: rit list credential > check3.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check3.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert3.txt
            expected_result: PASSED

  windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            choco install make
            make build-windows && move D:\a\ritchie-cli\ritchie-cli\dist\windows\rit.exe "D:\a\ritchie-cli\ritchie-cli"
            ls
            .\rit.exe init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT LIST CREDENTIAL command (1)
          run: .\rit.exe list credential > check1.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check1.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT SET CREDENTIAL command
          run: .\rit.exe set credential --provider=github --fields=username,email,token --values=test,test,test
        - name: RIT LIST CREDENTIAL command (2)
          run: .\rit.exe list credential > check2.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check2.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT DELETE CREDENTIAL command
          run: .\rit.exe delete credential --provider=github
        - name: RIT LIST CREDENTIAL command (3)
          run: .\rit.exe list credential > check3.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check3.txt
            second_file_path: testdata/gha_workflows/credential_workflow/assert3.txt
            expected_result: PASSED
