name: Test Credential Commands

on:
  workflow_dispatch: # Can be triggered manually through the ACTIONS tab on Github GUI.

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
            echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin
        - name: RIT LIST CREDENTIAL command (1)
          run:  |
            rit list credential > check1.txt
            diff check1.txt testdata/gha_workflows/credential_workflow/assert1.txt
        - name: RIT SET CREDENTIAL command
          run: rit set credential --provider=github --fields=username,email,token --values=test,test,test
        - name: RIT LIST CREDENTIAL command (2)
          run:  |
            rit list credential > check2.txt
            diff check2.txt testdata/gha_workflows/repo_workflow/assert2.txt
        - name: RIT DELETE CREDENTIAL command
          run: rit delete credential --provider=github
        - name: RIT LIST CREDENTIAL command (3)
          run:  |
            rit list credential > check3.txt
            diff check3.txt testdata/gha_workflows/repo_workflow/assert1.txt