name: Test Env Commands

# TXT files used for ASSERT are located on the /testdata/gha_workflows directory.

# To help you coding your workflow tests, you can use CAT commands to show each file you will compare on the workflow window on Github.

# EXAMPLE:
#   rit show env > check1.txt
#   cat check1.txt
#   cat testdata/gha_workflows/env_workflow/assert1.txt
#   diff check1.txt testdata/gha_workflows/env_workflow/assert1.txt

on:
  workflow_dispatch: # Can be triggered manually through the ACTIONS tab on Github GUI.
  push:
    paths: # Will trigger on PUSH event that update at least one of those files.
      - '**/cmd.go'
      - '**/delete_test.go'
      - '**/delete.go'
      - '**/delete_env_test.go'
      - '**/delete_env.go'
      - '**/set_env_test.go'
      - '**/set_env.go'
      - '**/set_test.go'
      - '**/set.go'
      - '**/show_env_test.go'
      - '**/show_env.go'
      - '**/show_test.go'
      - '**/show.go'
      - 'testdata/gha_workflows/env_workflow/**'
      - '**/test-env-commands.yml'

  pull_request:
    paths: # Will trigger on PULL_REQUEST event that update at least one of those files.
      - '**/cmd.go'
      - '**/delete_test.go'
      - '**/delete.go'
      - '**/delete_env_test.go'
      - '**/delete_env.go'
      - '**/set_env_test.go'
      - '**/set_env.go'
      - '**/set_test.go'
      - '**/set.go'
      - '**/show_env_test.go'
      - '**/show_env.go'
      - '**/show_test.go'
      - '**/show.go'
      - 'testdata/gha_workflows/env_workflow/**'
      - '**/test-env-commands.yml'

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
            rit init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT SHOW ENV command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT SET ENV command
          run: rit set env --env=test
        - name: RIT SHOW ENV command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT DELETE ENV command
          run: rit delete env --env=test
        - name: RIT SHOW ENV command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert1.txt
            expected_result: PASSED

  macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-mac && sudo mv ./dist/darwin/rit /usr/local/bin
            rit init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT SHOW ENV command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT SET ENV command
          run: rit set env --env=test
        - name: RIT SHOW ENV command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT DELETE ENV command
          run: rit delete env --env=test
        - name: RIT SHOW ENV command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert1.txt
            expected_result: PASSED

  windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            choco install make
            make build-windows && move D:\a\ritchie-cli\ritchie-cli\dist\windows\rit.exe "D:\a\ritchie-cli\ritchie-cli"
            ls
            .\rit.exe init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT SHOW ENV command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT SET ENV command
          run: ./rit.exe set env --env=test
        - name: RIT SHOW ENV command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT DELETE ENV command
          run: ./rit.exe delete env --env=test
        - name: RIT SHOW ENV command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe show env
            assert_file_path: testdata/gha_workflows/env_workflow/assert1.txt
            expected_result: PASSED
