name: Test Formula Commands

on: [workflow_dispatch, push]

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
        - name: RIT INIT without commons repo
          run:
            rit init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT CREATE FORMULA command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit create formula --name="rit functional test" --language="python3" --workspace="Default"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert1.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT INIT with COMMONS repo
          run:  rit init --sendMetrics="no" --addCommons="yes" --runType="local"
        - name: RIT CREATE FORMULA command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit create formula --name="rit functional test" --language="python3" --workspace="Default"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert2.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT RENAME FORMULA command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit rename formula --oldName="rit functional test" --newName="rit demo test"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert3.txt
            expected_result: PASSED
        - name: RIT DELETE FORMULA command (4)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit delete formula --workspace="Default" --formula="rit demo test"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert4.txt
            expected_result: PASSED

  macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-mac && sudo mv ./dist/darwin/rit /usr/local/bin
        - name: RIT INIT without commons repo
          run:
            rit init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT CREATE FORMULA command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit create formula --name="rit functional test" --language="python3" --workspace="Default"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert1.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT INIT with COMMONS repo
          run:  rit init --sendMetrics="no" --addCommons="yes" --runType="local"
        - name: RIT CREATE FORMULA command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit create formula --name="rit functional test" --language="python3" --workspace="Default"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert2.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT RENAME FORMULA command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit rename formula --oldName="rit functional test" --newName="rit demo test"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert3.txt
            expected_result: PASSED
        - name: RIT DELETE FORMULA command (4)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit delete formula --workspace="Default" --formula="rit demo test"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert4.txt
            expected_result: PASSED

  windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'       
        - name: Create binary from branch
          run: |
            choco install make
            make build-windows && move D:\a\ritchie-cli\ritchie-cli\dist\windows\rit.exe "D:\a\ritchie-cli\ritchie-cli"
            ls
        - name: RIT INIT without commons repo
          run:
            ./rit.exe init --sendMetrics="no" --addCommons="no" --runType="local"
        - name: RIT CREATE FORMULA command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe create formula --name="rit functional test" --language="python3" --workspace="Default"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert1.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT INIT with COMMONS repo
          run:  ./rit.exe init --sendMetrics="no" --addCommons="yes" --runType="local"
        - name: RIT CREATE FORMULA command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe create formula --name="rit functional test" --language="python3" --workspace="Default"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert2.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT RENAME FORMULA command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe rename formula --oldName="rit functional test" --newName="rit demo test"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert3.txt
            expected_result: PASSED
        - name: RIT DELETE FORMULA command (4)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe delete formula --workspace="Default" --formula="rit demo test"
            assert_file_path: testdata/gha_workflows/formula_workflow/assert4.txt
            expected_result: PASSED
