name: Test CLI binary

on:
  workflow_dispatch:

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
            echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin
        - name: Check RIT Binary Substitution
          run: |
            cd /usr/local/bin
            stat rit -c %y
        - name: RIT LIST REPO command (1)
          run:  |
            rit list repo > check1.txt
            cat check1.txt
            cat testdata/gha_workflows/repo_workflow/assert1.txt
            diff check1.txt testdata/gha_workflows/repo_workflow/assert1.txt
        - name: RIT ADD REPO command
          run: rit add repo --provider="Github" --name="demo" --repoUrl="https://github.com/ZupIT/ritchie-formulas-demo" --priority=1 --tag="2.2.0"
        - name: RIT LIST REPO command (2)
          run:  |
            rit list repo > check2.txt
            cat check2.txt
            cat testdata/gha_workflows/repo_workflow/assert2.txt
            diff check2.txt testdata/gha_workflows/repo_workflow/assert2.txt
        - name: RIT UPDATE REPO command
          run: rit update repo --name="demo" --version="2.3.0"
        - name: RIT LIST REPO command (3)
          run:  |
            rit list repo > check3.txt
            cat check3.txt
            cat testdata/gha_workflows/repo_workflow/assert3.txt
            diff check3.txt testdata/gha_workflows/repo_workflow/assert3.txt
        - name: RIT DELETE REPO command
          run: rit delete repo --name="demo"
        - name: RIT LIST REPO command (4)
          run:  |
            rit list repo > check4.txt
            cat check4.txt
            cat testdata/gha_workflows/repo_workflow/assert1.txt
            diff check4.txt testdata/gha_workflows/repo_workflow/assert1.txt

  macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-mac && sudo mv ./dist/darwin/rit /usr/local/bin
            echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin
        - name: RIT LIST REPO command (1)
          run:  |
            rit list repo > check1.txt
            cat check1.txt
            cat testdata/gha_workflows/repo_workflow/assert1.txt
            diff check1.txt testdata/gha_workflows/repo_workflow/assert1.txt
        - name: RIT ADD REPO command
          run: rit add repo --provider="Github" --name="demo" --repoUrl="https://github.com/ZupIT/ritchie-formulas-demo" --priority=1 --tag="2.2.0"
        - name: RIT LIST REPO command (2)
          run:  |
            rit list repo > check2.txt
            cat check2.txt
            cat testdata/gha_workflows/repo_workflow/assert2.txt
            diff check2.txt testdata/gha_workflows/repo_workflow/assert2.txt
        - name: RIT UPDATE REPO command
          run: rit update repo --name="demo" --version="2.3.0"
        - name: RIT LIST REPO command (3)
          run:  |
            rit list repo > check3.txt
            cat check3.txt
            cat testdata/gha_workflows/repo_workflow/assert3.txt
            diff check3.txt testdata/gha_workflows/repo_workflow/assert3.txt
        - name: RIT DELETE REPO command
          run: rit delete repo --name="demo"
        - name: RIT LIST REPO command (4)
          run:  |
            rit list repo > check4.txt
            cat check4.txt
            cat testdata/gha_workflows/repo_workflow/assert1.txt
            diff check4.txt testdata/gha_workflows/repo_workflow/assert1.txt

  windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            choco install make
            # ls
            # cd $GITHUB_WORKSPACE
            ls
            make build-windows && runas \user:administrator move .\dist\windows\rit.exe ".\"
            echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit.exe init --stdin
        - name: RIT LIST REPO command (1)
          run:  |
            rit.exe list repo
          # rit list repo > check1.txt
          # cat check1.txt
          # cat testdata/gha_workflows/repo_workflow/assert1.txt
          # diff check1.txt testdata/gha_workflows/repo_workflow/assert1.txt
        # - name: RIT ADD REPO command
        #   run: rit add repo --provider="Github" --name="demo" --repoUrl="https://github.com/ZupIT/ritchie-formulas-demo" --priority=1 --tag="2.2.0"
        # - name: RIT LIST REPO command (2)
        #   run:  |
        #     rit list repo > check2.txt
        #     cat check2.txt
        #     cat testdata/gha_workflows/repo_workflow/assert2.txt
        #     diff check2.txt testdata/gha_workflows/repo_workflow/assert2.txt
        # - name: RIT UPDATE REPO command
        #   run: rit update repo --name="demo" --version="2.3.0"
        # - name: RIT LIST REPO command (3)
        #   run:  |
        #     rit list repo > check3.txt
        #     cat check3.txt
        #     cat testdata/gha_workflows/repo_workflow/assert3.txt
        #     diff check3.txt testdata/gha_workflows/repo_workflow/assert3.txt
        # - name: RIT DELETE REPO command
        #   run: rit delete repo --name="demo"
        # - name: RIT LIST REPO command (4)
        #   run:  |
        #     rit list repo > check4.txt
        #     cat check4.txt
        #     cat testdata/gha_workflows/repo_workflow/assert1.txt
        #     diff check4.txt testdata/gha_workflows/repo_workflow/assert1.txt
