name: Test Commands

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
        - uses: GuillaumeFalourd/command-output-file-action@v1
          with:
            command_line: rit init --sendMetrics="no" --addCommons="no" --runType="local"
            output_file_name: check1.txt
            display_file_content: NO
        - run: cat check1.txt
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check1.txt
            second_file_path: testdata/gha_workflows/global_workflow/assert1.txt
            expected_result: PASSED
        - uses: GuillaumeFalourd/command-output-file-action@v1
          with:
            command_line: rit upgrade
            output_file_name: check2.txt
            display_file_content: NO
        - run: cat check2.txt
        - run: diff check2.txt testdata/gha_workflows/global_workflow/assert8.txt --color=none
        - uses: GuillaumeFalourd/diff-action@v1
          with:
            first_file_path: check2.txt
            second_file_path: testdata/gha_workflows/global_workflow/assert8.txt
            expected_result: PASSED
